// packages/svelte/src/lib/CSSRuntimeProvider.svelte
<script lang="ts">
    import { onMount, setContext } from 'svelte';
    import { writable, get } from 'svelte/store';
    import type { Config } from '@master/css';
    import { RuntimeCSS } from '@master/css-runtime';

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    export let config: Config | Promise<any> | undefined;
    export let root: Document | ShadowRoot | undefined;

    const runtimeCSSSymbol = Symbol('runtime-css');
    const runtimeCSS = writable<RuntimeCSS | undefined>(undefined);

    const resolveConfig = async () => {
        const configModule = await config;
        return configModule?.config || configModule?.default || configModule;
    };

    const initialize = async (signal: AbortSignal) => {
        const resolvedConfig = await resolveConfig();
        if (signal.aborted) return;
        runtimeCSS.set(new RuntimeCSS(root ?? document, resolvedConfig).observe());
    };

    let controller: AbortController | null = null;

    onMount(() => {
        controller = new AbortController();
        initialize(controller.signal);

        return () => {
            controller?.abort();
            const currentRuntimeCSS = get(runtimeCSS);
            currentRuntimeCSS?.destroy();
            runtimeCSS.set(undefined);
        };
    });

    $: (async () => {
        if (!config) return;
        const controller = new AbortController();
        const resolvedConfig = await resolveConfig();
        if (controller.signal.aborted) return;
        const currentRuntimeCSS = get(runtimeCSS);
        if (currentRuntimeCSS) {
            currentRuntimeCSS.refresh(resolvedConfig);
        }
    })();

    $: (async () => {
        if (!root) return;
        const controller = new AbortController();
        const currentRuntimeCSS = get(runtimeCSS);
        if (controller.signal.aborted) return;
        if (currentRuntimeCSS) {
            currentRuntimeCSS.destroy();
            runtimeCSS.set(undefined);
            initialize(controller.signal);
        }
    })();

    setContext(runtimeCSSSymbol, runtimeCSS);
</script>

<slot />

// packages/vue/src/CSSRuntimeProvider.vue
<script setup lang="ts">
import { ref, provide, onMounted, onUnmounted, watch, onWatcherCleanup } from 'vue';
import type { Config } from '@master/css';
import { RuntimeCSS } from '@master/css-runtime';

const RuntimeCSSSymbol = Symbol('runtime-css');
const props = defineProps<{
    config?: Config | Promise<any>;
    root?: Document | ShadowRoot;
}>();

const runtimeCSS = ref<RuntimeCSS | undefined>(undefined);

const resolveConfig = async () => {
    const configModule = await props.config;
    return configModule?.config || configModule?.default || configModule;
}

const initialize = async (signal: AbortSignal) => {
    const resolvedConfig = await resolveConfig();
    if (signal.aborted) return;
    runtimeCSS.value = new RuntimeCSS(props.root ?? document, resolvedConfig).observe();
}

onMounted(() => {
    const controller = new AbortController()
    initialize(controller.signal)
    onUnmounted(() => {
        controller.abort()
        runtimeCSS.value?.destroy()
        runtimeCSS.value = undefined
    })
})

watch(() => props.config, () => {
    const controller = new AbortController();
    (async () => {
        const resolvedConfig = await resolveConfig()
        if (controller.signal.aborted) return;
        if (runtimeCSS.value) {
            runtimeCSS.value.refresh(resolvedConfig)
        }
    })()
    onWatcherCleanup(controller.abort)
})

watch(() => props.root, () => {
    const controller = new AbortController();
    (async () => {
        if (controller.signal.aborted) return
        if (runtimeCSS.value) {
            runtimeCSS.value.destroy()
            runtimeCSS.value = undefined
            initialize(controller.signal)
        }
    })()
    onWatcherCleanup(controller.abort)
})

provide(RuntimeCSSSymbol, runtimeCSS.value)
</script>

<template>
    <slot />
</template>
